-- ==========================================
-- BioLink Schema & Data Export for Supabase SQL Editor
-- Target Database: PostgreSQL (Supabase)
-- Generated on: 2026-08-12T16:50:18.598Z
-- ==========================================

-- Enable UUID extension (optional, for utility)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Drop existing tables in reverse dependency order
DROP TABLE IF EXISTS "clicks" CASCADE;
DROP TABLE IF EXISTS "views" CASCADE;
DROP TABLE IF EXISTS "domains" CASCADE;
DROP TABLE IF EXISTS "video" CASCADE;
DROP TABLE IF EXISTS "music" CASCADE;
DROP TABLE IF EXISTS "gallery" CASCADE;
DROP TABLE IF EXISTS "links" CASCADE;
DROP TABLE IF EXISTS "bios" CASCADE;
DROP TABLE IF EXISTS "settings" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;

-- 1. USERS TABLE
CREATE TABLE "users" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" VARCHAR(255) UNIQUE NOT NULL,
    "email" VARCHAR(255) UNIQUE NOT NULL,
    "password" TEXT NOT NULL,
    "role" VARCHAR(50) DEFAULT 'user' CHECK ("role" IN ('user', 'admin', 'mod')),
    "displayName" VARCHAR(255),
    "avatarUrl" TEXT,
    "oauthProvider" VARCHAR(50),
    "oauthId" VARCHAR(255),
    "suspended" INT DEFAULT 0,
    "createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 2. BIOS TABLE
CREATE TABLE "bios" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userId" BIGINT NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
    "username" VARCHAR(255) UNIQUE NOT NULL,
    "displayName" VARCHAR(255),
    "tagline" TEXT,
    "bio" TEXT,
    "pronouns" VARCHAR(100),
    "avatarUrl" TEXT,
    "theme" VARCHAR(100) DEFAULT 'dark',
    "accentColor" VARCHAR(50) DEFAULT '#7c6aff',
    "btnStyle" VARCHAR(50) DEFAULT 'pill',
    "location" VARCHAR(255),
    "showViews" INT DEFAULT 1,
    "published" INT DEFAULT 1,
    "customDomain" VARCHAR(255),
    "domainVerified" INT DEFAULT 0,
    "domainToken" TEXT,
    "bgType" VARCHAR(50) DEFAULT 'gradient',
    "bgValue" TEXT,
    "particlesEnabled" INT DEFAULT 0,
    "cursorTrail" INT DEFAULT 0,
    "snowEnabled" INT DEFAULT 0,
    "bgVideo" TEXT,
    "customCSS" TEXT,
    "audioUrl" TEXT,
    "socials" JSONB DEFAULT '{}'::jsonb,
    "seoTitle" VARCHAR(255),
    "seoDesc" TEXT,
    "seoImage" TEXT,
    "updatedAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 3. LINKS TABLE
CREATE TABLE "links" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userId" BIGINT NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
    "title" VARCHAR(255) NOT NULL,
    "url" TEXT NOT NULL,
    "description" TEXT,
    "icon" VARCHAR(100),
    "tag" VARCHAR(100),
    "password" VARCHAR(255),
    "sortOrder" INT DEFAULT 0,
    "active" INT DEFAULT 1
);

-- 4. GALLERY TABLE
CREATE TABLE "gallery" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userId" BIGINT NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
    "imageUrl" TEXT NOT NULL,
    "caption" TEXT,
    "sortOrder" INT DEFAULT 0
);

-- 5. MUSIC TABLE
CREATE TABLE "music" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userId" BIGINT NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
    "type" VARCHAR(50) NOT NULL CHECK ("type" IN ('spotify', 'soundcloud')),
    "url" TEXT NOT NULL,
    "autoplay" INT DEFAULT 0
);

-- 6. VIDEO TABLE
CREATE TABLE "video" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userId" BIGINT NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
    "type" VARCHAR(50) NOT NULL CHECK ("type" IN ('youtube', 'vimeo', 'mp4')),
    "url" TEXT NOT NULL,
    "title" VARCHAR(255)
);

-- 7. VIEWS TABLE
CREATE TABLE "views" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userId" BIGINT NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
    "date" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    "ip" VARCHAR(100),
    "referrer" TEXT
);

-- 8. CLICKS TABLE
CREATE TABLE "clicks" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "linkId" BIGINT NOT NULL REFERENCES "links"("id") ON DELETE CASCADE,
    "date" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    "ip" VARCHAR(100)
);

-- 9. SETTINGS TABLE
CREATE TABLE "settings" (
    "id" INT PRIMARY KEY CHECK ("id" = 1),
    "platformName" VARCHAR(255) DEFAULT 'BioLink',
    "allowRegister" INT DEFAULT 1,
    "showViews" INT DEFAULT 1,
    "maintenance" INT DEFAULT 0
);

-- 10. DOMAINS TABLE
CREATE TABLE "domains" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userId" BIGINT NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
    "domain" VARCHAR(255) NOT NULL,
    "verified" INT DEFAULT 0,
    "createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ==========================================
-- SEED / EXISTING DATA INSERTS
-- ==========================================

-- Data for table: users
INSERT INTO "users" ("id", "username", "email", "password", "role", "displayName", "avatarUrl", "oauthProvider", "oauthId", "suspended", "createdAt") VALUES (1, 'admin', 'admin@biolink.local', '$2b$10$SYuvtNODvavNSJXagDahle64dU.u0UXv2VRt8C1cXmgo4nMVdR0li', 'admin', 'Platform Admin', NULL, NULL, NULL, 0, '2026-08-12 13:29:46') ON CONFLICT DO NOTHING;
INSERT INTO "users" ("id", "username", "email", "password", "role", "displayName", "avatarUrl", "oauthProvider", "oauthId", "suspended", "createdAt") VALUES (2, 'test1', 'test1@a.com', 'hash', 'user', 'test1', NULL, NULL, NULL, 0, '2026-08-12 14:06:06') ON CONFLICT DO NOTHING;

-- Data for table: bios
INSERT INTO "bios" ("id", "userId", "username", "displayName", "tagline", "bio", "pronouns", "avatarUrl", "theme", "accentColor", "btnStyle", "location", "showViews", "published", "customDomain", "domainVerified", "bgType", "bgValue", "particlesEnabled", "cursorTrail", "snowEnabled", "bgVideo", "customCSS", "audioUrl", "socials", "seoTitle", "seoDesc", "seoImage", "updatedAt", "domainToken") VALUES (1, 1, 'admin', 'Platform Admin', 'Builder of the future', 'Welcome to the premium bio-link platform.', NULL, NULL, 'cyber', '#7c6aff', 'pill', NULL, 1, 1, NULL, 0, 'gradient', NULL, 1, 0, 0, NULL, NULL, NULL, '{}'::jsonb, 'BioLink Admin', 'Premium bio-link platform', NULL, '2026-08-12 13:29:46', NULL) ON CONFLICT DO NOTHING;

-- Data for table: settings
INSERT INTO "settings" ("id", "platformName", "allowRegister", "showViews", "maintenance") VALUES (1, 'BioLink', 1, 1, 0) ON CONFLICT DO NOTHING;

-- Reset primary key sequences for PostgreSQL identity columns
SELECT setval(pg_get_serial_sequence('"users"', 'id'), COALESCE((SELECT MAX("id") FROM "users"), 1), true);
SELECT setval(pg_get_serial_sequence('"bios"', 'id'), COALESCE((SELECT MAX("id") FROM "bios"), 1), true);
SELECT setval(pg_get_serial_sequence('"links"', 'id'), COALESCE((SELECT MAX("id") FROM "links"), 1), true);
SELECT setval(pg_get_serial_sequence('"gallery"', 'id'), COALESCE((SELECT MAX("id") FROM "gallery"), 1), true);
SELECT setval(pg_get_serial_sequence('"music"', 'id'), COALESCE((SELECT MAX("id") FROM "music"), 1), true);
SELECT setval(pg_get_serial_sequence('"video"', 'id'), COALESCE((SELECT MAX("id") FROM "video"), 1), true);
SELECT setval(pg_get_serial_sequence('"views"', 'id'), COALESCE((SELECT MAX("id") FROM "views"), 1), true);
SELECT setval(pg_get_serial_sequence('"clicks"', 'id'), COALESCE((SELECT MAX("id") FROM "clicks"), 1), true);
SELECT setval(pg_get_serial_sequence('"domains"', 'id'), COALESCE((SELECT MAX("id") FROM "domains"), 1), true);
